disabled_rules:
    # コードの記載のない改行を許可したい
    - trailing_whitespace

    # ネスト1つで怒られるのでDisableにしたい
    - nesting

    # 強制キャストを許可したい
    - force_cast
    - opening_brace

    # 型名や変数に_を使えるように
    - type_name
    - identifier_name

    # 連続した空行を許可
    - vertical_whitespace

    # ファイル末尾の改行を許可
    - trailing_newline

    - force_try

# Lint対象にするファイル
included:
    - ../SwiftMoji

# 1行あたりの文字数制限を300に変更
# プロジェクト作成時にデフォルトで追加されるコメントをひっかけないため
line_length: 300

# 1ファイルあたりの行数制限を500に変更
file_length: 800

# 型内の行数を500に変更
type_body_length: 500

# 識別子の長さのMAXとMINを変更
identifier_name:
  max_length:
    warning: 60
    error: 80
  min_length:
    warning: 1
    error: 0
