source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'SwiftLint'

target 'SwiftMoji_Example' do
  pod 'SwiftMoji', :path => '../'
end

target 'SwiftMoji_Tests' do
  pod 'SwiftMoji', :path => '../'
end
