env:
  global:
    - LC_CTYPE=en_US.UTF-8
  matrix: 
    - TEST_SDK=iphonesimulator12.2 OS=12.2 NAME='iPhone 7'

language: objective-c
osx_image: xcode10.2
cache: cocoapods
podfile: Example/Podfile

before_install:
  - bundle install --path vendor/bundle
  - bundle exec pod --version
  - bundle exec pod install --project-directory=Example

script:
  - bundle exec pod lib lint
  - set -o pipefail
  - xcodebuild build-for-testing test-without-building -workspace Example/SwiftMoji.xcworkspace -scheme SwiftMoji-Example -configuration Release -sdk $TEST_SDK -destination "platform=iOS Simulator,name=$NAME,OS=$OS" ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat /Users/travis/Library/Developer/Xcode/DerivedData/SwiftMoji-*/Logs/Test/Test-SwiftMoji-Example-*/**/Diagnostics/SwiftMoji_Tests-*/SwiftMoji_Tests-*/Session-SwiftMoji_Tests-*.log