env:
  global:
    - LC_CTYPE=en_US.UTF-8

language: objective-c
osx_image: xcode8.1
cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod --version
  - gem uninstall cocoapods -a
  - gem install -v 1.1.1 cocoapods
  - pod --version
  - pod install --project-directory=Example

script:
  - pod lib lint
  - set -o pipefail
  - xcodebuild build-for-testing test-without-building -workspace Example/SwiftMoji.xcworkspace -scheme SwiftMoji-Example -configuration Release -sdk iphonesimulator -destination "name=iPhone 6s" ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
