env:
  global:
    - LC_CTYPE=en_US.UTF-8
  matrix: 
    - TEST_SDK=iphonesimulator13.2 OS=13.2 NAME='iPhone 8' 

language: objective-c
osx_image: xcode11.3
cache: cocoapods
podfile: Example/Podfile

before_install:
  - bundle install --path vendor/bundle
  - bundle exec pod --version
  - bundle exec pod install --project-directory=Example

script:
  - bundle exec pod lib lint
  - set -o pipefail
  - xcodebuild build-for-testing test-without-building -workspace Example/SwiftMoji.xcworkspace -scheme SwiftMoji-Example -configuration Release -sdk $TEST_SDK -destination "platform=iOS Simulator, name=iPhone 8,OS=13.2" ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
