# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
cache: cocoapods
podfile: Example/Podfile
xcode_sdk: iphonesimulator10.0

before_install:
  - pod --version
  - gem uninstall cocoapods -a
  - gem install -v 1.1.1 cocoapods
  - pod --version
  - pod install --project-directory=Example

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - pod lib lint
  - set -o pipefail
  - xcodebuild clean build -workspace Example/SwiftMoji.xcworkspace -scheme SwiftMoji-Example -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
  - xcodebuild test -workspace Example/SwiftMoji.xcworkspace -scheme SwiftMoji-Example -configuration Debug  -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
